### PR TITLE
Build a 2.x archetype rather than on old (1.x) Archetype (#6)

### PR DESCRIPTION
**Pull request by sewe**
To do so, this change switches from the old `archetype.xml` to the new `archetype-metadata.xml` descriptor format.

### CODE REVIEW

**Comment by KengoTODA** [comment]
I will check. BTW where you find the information about archetype version 2? I found that offical site introduces only about version 1 format.

https://maven.apache.org/guides/mini/guide-creating-archetypes.html

**Comment by sewe** [comment]
> BTW where you find the information about archetype version 2? I found that offical site introduces only about version 1 format.

The version 2 format is documented [here](https://maven.apache.org/archetype-archives/archetype-2.1/archetype-models/archetype-descriptor/archetype-descriptor.html), alongside all [other archetype-related XML vocabularies](https://maven.apache.org/archetype-archives/archetype-2.1/archetype-common/).

FWIW, updating the guide in the official site is bug [ARCHETYPE-451](https://issues.apache.org/jira/browse/ARCHETYPE-451) already.

**Comment by KengoTODA** [comment]
Good, thanks. I will check them. If possible, we want to add one more source folder for case classes to separate test class and case class.

**Comment by sewe** [comment]
> If possible, we want to add one more source folder for case classes to separate test class and case class. I hope that v2 supports this requirement.

I don’t this this has anything to do with the version; the archetype can put files in as many directories as you like. **However**, Maven traditionally supports only one `${project.build.sourceDirectory}` and one `${project.build.testSourceDirectory}` (see the [POM Reference](http://maven.apache.org/pom.html#Directories)); if you want more than one test source directory, you will need the [`build-helper-maven-plugin`](http://www.mojohaus.org/build-helper-maven-plugin/add-test-source-mojo.html).

Personally, I would simply use a different package, e.g., `test.*`, for the test data. (FYI, the `test` top-level domain is reserved by [RFC 6761](https://tools.ietf.org/html/rfc6761)).

**Comment by KengoTODA** [comment]
> you will need the build-helper-maven-plugin.

Yes I know. In my understanding v1 let us use `src/main/java` and `src/test/java` but there is no option to add more like `src/case/java`, this is the problem what I faced.

About package, let's have separated discussion with @jsotuyod later.

**Pull request merged**
